name: Update gradle.properties

on:
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update gradle.properties
      run: |
        echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" > gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties
        echo "org.gradle.configureondemand=true" >> gradle.properties
        echo "org.gradle.caching=true" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "kotlin.code.style=official" >> gradle.properties
        echo "android.nonTransitiveRClass=true" >> gradle.properties
        echo "android.suppressUnsupportedCompileSdk=34" >> gradle.properties

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add gradle.properties
        git commit -m 'Update gradle.properties with new settings'
        git push
